// Generated by gencpp from file buggy_robot/Command.msg
// DO NOT EDIT!


#ifndef BUGGY_ROBOT_MESSAGE_COMMAND_H
#define BUGGY_ROBOT_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Time.h>

namespace buggy_robot
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : stamp()
    , cmd(0.0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : stamp(_alloc)
    , cmd(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Time_<ContainerAllocator>  _stamp_type;
  _stamp_type stamp;

   typedef double _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::buggy_robot::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::buggy_robot::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::buggy_robot::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::buggy_robot::Command > CommandPtr;
typedef boost::shared_ptr< ::buggy_robot::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::buggy_robot::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::buggy_robot::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::buggy_robot::Command_<ContainerAllocator1> & lhs, const ::buggy_robot::Command_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::buggy_robot::Command_<ContainerAllocator1> & lhs, const ::buggy_robot::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace buggy_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::buggy_robot::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::buggy_robot::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::buggy_robot::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::buggy_robot::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::buggy_robot::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::buggy_robot::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::buggy_robot::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74f77447b8a55be4787813997e92e85b";
  }

  static const char* value(const ::buggy_robot::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74f77447b8a55be4ULL;
  static const uint64_t static_value2 = 0x787813997e92e85bULL;
};

template<class ContainerAllocator>
struct DataType< ::buggy_robot::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "buggy_robot/Command";
  }

  static const char* value(const ::buggy_robot::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::buggy_robot::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Time stamp\n"
"float64 cmd\n"
"================================================================================\n"
"MSG: std_msgs/Time\n"
"time data\n"
;
  }

  static const char* value(const ::buggy_robot::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::buggy_robot::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::buggy_robot::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::buggy_robot::Command_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    s << std::endl;
    Printer< ::std_msgs::Time_<ContainerAllocator> >::stream(s, indent + "  ", v.stamp);
    s << indent << "cmd: ";
    Printer<double>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUGGY_ROBOT_MESSAGE_COMMAND_H
