// Generated by gencpp from file buggy_robot/SetTarget.msg
// DO NOT EDIT!


#ifndef BUGGY_ROBOT_MESSAGE_SETTARGET_H
#define BUGGY_ROBOT_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <buggy_robot/SetTargetRequest.h>
#include <buggy_robot/SetTargetResponse.h>


namespace buggy_robot
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace buggy_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::buggy_robot::SetTarget > {
  static const char* value()
  {
    return "4e189454548dc258e2bec03d6806f911";
  }

  static const char* value(const ::buggy_robot::SetTarget&) { return value(); }
};

template<>
struct DataType< ::buggy_robot::SetTarget > {
  static const char* value()
  {
    return "buggy_robot/SetTarget";
  }

  static const char* value(const ::buggy_robot::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::buggy_robot::SetTargetRequest> should match
// service_traits::MD5Sum< ::buggy_robot::SetTarget >
template<>
struct MD5Sum< ::buggy_robot::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::buggy_robot::SetTarget >::value();
  }
  static const char* value(const ::buggy_robot::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::buggy_robot::SetTargetRequest> should match
// service_traits::DataType< ::buggy_robot::SetTarget >
template<>
struct DataType< ::buggy_robot::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::buggy_robot::SetTarget >::value();
  }
  static const char* value(const ::buggy_robot::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::buggy_robot::SetTargetResponse> should match
// service_traits::MD5Sum< ::buggy_robot::SetTarget >
template<>
struct MD5Sum< ::buggy_robot::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::buggy_robot::SetTarget >::value();
  }
  static const char* value(const ::buggy_robot::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::buggy_robot::SetTargetResponse> should match
// service_traits::DataType< ::buggy_robot::SetTarget >
template<>
struct DataType< ::buggy_robot::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::buggy_robot::SetTarget >::value();
  }
  static const char* value(const ::buggy_robot::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUGGY_ROBOT_MESSAGE_SETTARGET_H
