// Generated by gencpp from file buggy_robot/SetTargetRequest.msg
// DO NOT EDIT!


#ifndef BUGGY_ROBOT_MESSAGE_SETTARGETREQUEST_H
#define BUGGY_ROBOT_MESSAGE_SETTARGETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace buggy_robot
{
template <class ContainerAllocator>
struct SetTargetRequest_
{
  typedef SetTargetRequest_<ContainerAllocator> Type;

  SetTargetRequest_()
    : x_target(0.0)  {
    }
  SetTargetRequest_(const ContainerAllocator& _alloc)
    : x_target(0.0)  {
  (void)_alloc;
    }



   typedef double _x_target_type;
  _x_target_type x_target;





  typedef boost::shared_ptr< ::buggy_robot::SetTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::buggy_robot::SetTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetRequest_

typedef ::buggy_robot::SetTargetRequest_<std::allocator<void> > SetTargetRequest;

typedef boost::shared_ptr< ::buggy_robot::SetTargetRequest > SetTargetRequestPtr;
typedef boost::shared_ptr< ::buggy_robot::SetTargetRequest const> SetTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::buggy_robot::SetTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::buggy_robot::SetTargetRequest_<ContainerAllocator1> & lhs, const ::buggy_robot::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x_target == rhs.x_target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::buggy_robot::SetTargetRequest_<ContainerAllocator1> & lhs, const ::buggy_robot::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace buggy_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::buggy_robot::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::buggy_robot::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::buggy_robot::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "effe2ea1bbd5ee8d6c5cb4bb0fe9121b";
  }

  static const char* value(const ::buggy_robot::SetTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeffe2ea1bbd5ee8dULL;
  static const uint64_t static_value2 = 0x6c5cb4bb0fe9121bULL;
};

template<class ContainerAllocator>
struct DataType< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "buggy_robot/SetTargetRequest";
  }

  static const char* value(const ::buggy_robot::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_target\n"
;
  }

  static const char* value(const ::buggy_robot::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::buggy_robot::SetTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::buggy_robot::SetTargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_target: ";
    Printer<double>::stream(s, indent + "  ", v.x_target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BUGGY_ROBOT_MESSAGE_SETTARGETREQUEST_H
